#!/usr/bin/env bash
# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/^\(listen .*\)80;/\180;/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Create HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html
