#!/bin/bash

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy -y

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' << EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Enable HAProxy init script
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

